name: BuyableWorldGuardRegions
version: 1.0.0
author: Scusemua
main: me.Scusemua.BuyableWorldGuardRegions.Core.Main
depend: [WorldEdit, WorldGuard, Vault]
commands:
  protection:
    description: Base command for the buying of regions.
    usage: /<command>
    permissions: BuyableWorldGuardRegions.protection